In [1]:
!pip install Web3

Collecting Web3
  Downloading web3-7.11.0-py3-none-any.whl.metadata (5.6 kB)
Collecting eth-abi>=5.0.1 (from Web3)
  Downloading eth_abi-5.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting eth-account>=0.13.6 (from Web3)
  Downloading eth_account-0.13.7-py3-none-any.whl.metadata (3.7 kB)
Collecting eth-hash>=0.5.1 (from eth-hash[pycryptodome]>=0.5.1->Web3)
  Downloading eth_hash-0.7.1-py3-none-any.whl.metadata (4.2 kB)
Collecting eth-typing>=5.0.0 (from Web3)
  Downloading eth_typing-5.2.1-py3-none-any.whl.metadata (3.2 kB)
Collecting eth-utils>=5.0.0 (from Web3)
  Downloading eth_utils-5.3.0-py3-none-any.whl.metadata (5.7 kB)
Collecting hexbytes>=1.2.0 (from Web3)
  Downloading hexbytes-1.3.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: aiohttp>=3.7.4.post0 in /usr/local/lib/python3.11/dist-packages (from Web3) (3.11.15)
Requirement already satisfied: pydantic>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from Web3) (2.11.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from Web3) (2.32.3)
Requirement already satisfied: typing-extensions>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from Web3) (4.13.2)
Collecting types-requests>=2.0.0 (from Web3)
  Downloading types_requests-2.32.0.20250328-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: websockets<16.0.0,>=10.0.0 in /usr/local/lib/python3.11/dist-packages (from Web3) (15.0.1)
Collecting pyunormalize>=15.0.0 (from Web3)
  Downloading pyunormalize-16.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->Web3) (1.20.0)
Collecting parsimonious<0.11.0,>=0.10.0 (from eth-abi>=5.0.1->Web3)
  Downloading parsimonious-0.10.0-py3-none-any.whl.metadata (25 kB)
Collecting bitarray>=2.4.0 (from eth-account>=0.13.6->Web3)
  Downloading bitarray-3.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting eth-keyfile<0.9.0,>=0.7.0 (from eth-account>=0.13.6->Web3)
  Downloading eth_keyfile-0.8.1-py3-none-any.whl.metadata (8.5 kB)
Collecting eth-keys>=0.4.0 (from eth-account>=0.13.6->Web3)
  Downloading eth_keys-0.7.0-py3-none-any.whl.metadata (13 kB)
Collecting eth-rlp>=2.1.0 (from eth-account>=0.13.6->Web3)
  Downloading eth_rlp-2.2.0-py3-none-any.whl.metadata (3.3 kB)
Collecting rlp>=1.0.0 (from eth-account>=0.13.6->Web3)
  Downloading rlp-4.1.0-py3-none-any.whl.metadata (3.2 kB)
Collecting ckzg>=2.0.0 (from eth-account>=0.13.6->Web3)
  Downloading ckzg-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (887 bytes)
Collecting pycryptodome<4,>=3.6.6 (from eth-hash[pycryptodome]>=0.5.1->Web3)
  Downloading pycryptodome-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Collecting cytoolz>=0.10.1 (from eth-utils>=5.0.0->Web3)
  Downloading cytoolz-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->Web3) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->Web3) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->Web3) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->Web3) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->Web3) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->Web3) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->Web3) (2025.1.31)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from cytoolz>=0.10.1->eth-utils>=5.0.0->Web3) (0.12.1)
Requirement already satisfied: regex>=2022.3.15 in /usr/local/lib/python3.11/dist-packages (from parsimonious<0.11.0,>=0.10.0->eth-abi>=5.0.1->Web3) (2024.11.6)
Downloading web3-7.11.0-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 18.0 MB/s eta 0:00:00
Downloading eth_abi-5.2.0-py3-none-any.whl (28 kB)
Downloading eth_account-0.13.7-py3-none-any.whl (587 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.5/587.5 kB 19.0 MB/s eta 0:00:00
Downloading eth_hash-0.7.1-py3-none-any.whl (8.0 kB)
Downloading eth_typing-5.2.1-py3-none-any.whl (19 kB)
Downloading eth_utils-5.3.0-py3-none-any.whl (102 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.5/102.5 kB 3.6 MB/s eta 0:00:00
Downloading hexbytes-1.3.0-py3-none-any.whl (4.9 kB)
Downloading pyunormalize-16.0.0-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.2/49.2 kB 2.0 MB/s eta 0:00:00
Downloading types_requests-2.32.0.20250328-py3-none-any.whl (20 kB)
Downloading bitarray-3.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (306 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 306.6/306.6 kB 8.4 MB/s eta 0:00:00
Downloading ckzg-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (170 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.5/170.5 kB 5.2 MB/s eta 0:00:00
Downloading cytoolz-1.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 16.5 MB/s eta 0:00:00
Downloading eth_keyfile-0.8.1-py3-none-any.whl (7.5 kB)
Downloading eth_keys-0.7.0-py3-none-any.whl (20 kB)
Downloading eth_rlp-2.2.0-py3-none-any.whl (4.4 kB)
Downloading parsimonious-0.10.0-py3-none-any.whl (48 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 2.0 MB/s eta 0:00:00
Downloading pycryptodome-3.22.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 22.7 MB/s eta 0:00:00
Downloading rlp-4.1.0-py3-none-any.whl (19 kB)
Installing collected packages: ckzg, bitarray, types-requests, pyunormalize, pycryptodome, parsimonious, hexbytes, eth-typing, eth-hash, cytoolz, eth-utils, rlp, eth-keys, eth-abi, eth-rlp, eth-keyfile, eth-account, Web3
Successfully installed Web3-7.11.0 bitarray-3.3.1 ckzg-2.1.1 cytoolz-1.0.1 eth-abi-5.2.0 eth-account-0.13.7 eth-hash-0.7.1 eth-keyfile-0.8.1 eth-keys-0.7.0 eth-rlp-2.2.0 eth-typing-5.2.1 eth-utils-5.3.0 hexbytes-1.3.0 parsimonious-0.10.0 pycryptodome-3.22.0 pyunormalize-16.0.0 rlp-4.1.0 types-requests-2.32.0.20250328

In [2]:
!pip install eth_tester

Collecting eth_tester
  Downloading eth_tester-0.13.0b1-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: eth-abi>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from eth_tester) (5.2.0)
Requirement already satisfied: eth-account>=0.12.3 in /usr/local/lib/python3.11/dist-packages (from eth_tester) (0.13.7)
Requirement already satisfied: eth-keys>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from eth_tester) (0.7.0)
Requirement already satisfied: eth-utils>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from eth_tester) (5.3.0)
Requirement already satisfied: rlp>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from eth_tester) (4.1.0)
Collecting semantic_version>=2.6.0 (from eth_tester)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: eth-typing>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from eth-abi>=3.0.1->eth_tester) (5.2.1)
Requirement already satisfied: parsimonious<0.11.0,>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from eth-abi>=3.0.1->eth_tester) (0.10.0)
Requirement already satisfied: bitarray>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (3.3.1)
Requirement already satisfied: eth-keyfile<0.9.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (0.8.1)
Requirement already satisfied: eth-rlp>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (2.2.0)
Requirement already satisfied: hexbytes>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (1.3.0)
Requirement already satisfied: ckzg>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (2.1.1)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.12.3->eth_tester) (2.11.3)
Requirement already satisfied: eth-hash>=0.3.1 in /usr/local/lib/python3.11/dist-packages (from eth-utils>=2.0.0->eth_tester) (0.7.1)
Requirement already satisfied: cytoolz>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from eth-utils>=2.0.0->eth_tester) (1.0.1)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from cytoolz>=0.10.1->eth-utils>=2.0.0->eth_tester) (0.12.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from eth-keyfile<0.9.0,>=0.7.0->eth-account>=0.12.3->eth_tester) (3.22.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from eth-typing>=3.0.0->eth-abi>=3.0.1->eth_tester) (4.13.2)
Requirement already satisfied: regex>=2022.3.15 in /usr/local/lib/python3.11/dist-packages (from parsimonious<0.11.0,>=0.10.0->eth-abi>=3.0.1->eth_tester) (2024.11.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->eth-account>=0.12.3->eth_tester) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->eth-account>=0.12.3->eth_tester) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0.0->eth-account>=0.12.3->eth_tester) (0.4.0)
Downloading eth_tester-0.13.0b1-py3-none-any.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 4.7 MB/s eta 0:00:00
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Installing collected packages: semantic_version, eth_tester
Successfully installed eth_tester-0.13.0b1 semantic_version-2.10.0

In [3]:
!pip install "web3[tester]"

Requirement already satisfied: web3[tester] in /usr/local/lib/python3.11/dist-packages (7.11.0)
Requirement already satisfied: eth-abi>=5.0.1 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (5.2.0)
Requirement already satisfied: eth-account>=0.13.6 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (0.13.7)
Requirement already satisfied: eth-hash>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from eth-hash[pycryptodome]>=0.5.1->web3[tester]) (0.7.1)
Requirement already satisfied: eth-typing>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (5.2.1)
Requirement already satisfied: eth-utils>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (5.3.0)
Requirement already satisfied: hexbytes>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (1.3.0)
Requirement already satisfied: aiohttp>=3.7.4.post0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (3.11.15)
Requirement already satisfied: pydantic>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (2.11.3)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (2.32.3)
Requirement already satisfied: typing-extensions>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (4.13.2)
Requirement already satisfied: types-requests>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (2.32.0.20250328)
Requirement already satisfied: websockets<16.0.0,>=10.0.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (15.0.1)
Requirement already satisfied: pyunormalize>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from web3[tester]) (16.0.0)
Requirement already satisfied: eth-tester<0.14.0b1,>=0.13.0b1 in /usr/local/lib/python3.11/dist-packages (from eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester]) (0.13.0b1)
Collecting py-geth>=5.1.0 (from web3[tester])
  Downloading py_geth-5.4.0-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.7.4.post0->web3[tester]) (1.20.0)
Requirement already satisfied: parsimonious<0.11.0,>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from eth-abi>=5.0.1->web3[tester]) (0.10.0)
Requirement already satisfied: bitarray>=2.4.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (3.3.1)
Requirement already satisfied: eth-keyfile<0.9.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (0.8.1)
Requirement already satisfied: eth-keys>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (0.7.0)
Requirement already satisfied: eth-rlp>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (2.2.0)
Requirement already satisfied: rlp>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (4.1.0)
Requirement already satisfied: ckzg>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from eth-account>=0.13.6->web3[tester]) (2.1.1)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from eth-hash[pycryptodome]>=0.5.1->web3[tester]) (3.22.0)
Requirement already satisfied: semantic_version>=2.6.0 in /usr/local/lib/python3.11/dist-packages (from eth-tester<0.14.0b1,>=0.13.0b1->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester]) (2.10.0)
Collecting py-evm<0.13.0b1,>=0.12.0b2 (from eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading py_evm-0.12.0b3-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: cytoolz>=0.10.1 in /usr/local/lib/python3.11/dist-packages (from eth-utils>=5.0.0->web3[tester]) (1.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->web3[tester]) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->web3[tester]) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.4.0->web3[tester]) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->web3[tester]) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->web3[tester]) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->web3[tester]) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->web3[tester]) (2025.1.31)
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from cytoolz>=0.10.1->eth-utils>=5.0.0->web3[tester]) (0.12.1)
Collecting safe-pysha3>=1.0.0 (from eth-hash>=0.5.1->eth-hash[pycryptodome]>=0.5.1->web3[tester])
  Downloading safe-pysha3-1.0.4.tar.gz (827 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 827.7/827.7 kB 15.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: regex>=2022.3.15 in /usr/local/lib/python3.11/dist-packages (from parsimonious<0.11.0,>=0.10.0->eth-abi>=5.0.1->web3[tester]) (2024.11.6)
Collecting cached-property>=1.5.1 (from py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading cached_property-2.0.1-py3-none-any.whl.metadata (10 kB)
Collecting eth-bloom>=1.0.3 (from py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading eth_bloom-3.1.0-py3-none-any.whl.metadata (8.7 kB)
Collecting lru-dict>=1.1.6 (from py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading lru_dict-1.3.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.5 kB)
Collecting py-ecc>=8.0.0 (from py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading py_ecc-8.0.0-py3-none-any.whl.metadata (3.1 kB)
Collecting trie>=2.0.0 (from py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester])
  Downloading trie-3.1.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: sortedcontainers>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from trie>=2.0.0->py-evm<0.13.0b1,>=0.12.0b2->eth-tester[py-evm]<0.14.0b1,>=0.13.0b1; extra == "tester"->web3[tester]) (2.4.0)
Downloading py_geth-5.4.0-py3-none-any.whl (28 kB)
Downloading py_evm-0.12.0b3-py3-none-any.whl (798 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.6/798.6 kB 35.9 MB/s eta 0:00:00
Downloading cached_property-2.0.1-py3-none-any.whl (7.4 kB)
Downloading eth_bloom-3.1.0-py3-none-any.whl (5.8 kB)
Downloading lru_dict-1.3.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31 kB)
Downloading py_ecc-8.0.0-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 2.4 MB/s eta 0:00:00
Downloading trie-3.1.0-py3-none-any.whl (38 kB)
Building wheels for collected packages: safe-pysha3
  Building wheel for safe-pysha3 (setup.py) ... done
  Created wheel for safe-pysha3: filename=safe_pysha3-1.0.4-cp311-cp311-linux_x86_64.whl size=147640 sha256=ed0970d5145582e60d80434cbf472fb9607d0e86c6d3bf35dbb661f43d096ff6
  Stored in directory: /root/.cache/pip/wheels/b3/ef/41/7bba4fbb915ace87eea10e6a287a991a7ced54d98726906766
Successfully built safe-pysha3
Installing collected packages: safe-pysha3, lru-dict, cached-property, eth-bloom, py-geth, py-ecc, trie, py-evm
Successfully installed cached-property-2.0.1 eth-bloom-3.1.0 lru-dict-1.3.0 py-ecc-8.0.0 py-evm-0.12.0b3 py-geth-5.4.0 safe-pysha3-1.0.4 trie-3.1.0

In [4]:
!pip install py-solc-x

Collecting py-solc-x
  Downloading py_solc_x-2.0.3-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: requests<3,>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from py-solc-x) (2.32.3)
Collecting packaging<24,>=23.1 (from py-solc-x)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.19.0->py-solc-x) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.19.0->py-solc-x) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.19.0->py-solc-x) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.19.0->py-solc-x) (2025.1.31)
Downloading py_solc_x-2.0.3-py3-none-any.whl (18 kB)
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 3.7 MB/s eta 0:00:00
Installing collected packages: packaging, py-solc-x
  Attempting uninstall: packaging
    Found existing installation: packaging 24.2
    Uninstalling packaging-24.2:
      Successfully uninstalled packaging-24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-cloud-bigquery 3.31.0 requires packaging>=24.2.0, but you have packaging 23.2 which is incompatible.
Successfully installed packaging-23.2 py-solc-x-2.0.3

In [5]:
import hashlib
import json
import time
import pandas as pd
from cryptography.fernet import Fernet

# Generate/load symmetric encryption key
try:
    with open("secret.key", "rb") as f:
        key = f.read()
except FileNotFoundError:
    key = Fernet.generate_key()
    with open("secret.key", "wb") as f:
        f.write(key)

fernet = Fernet(key)

class Block:
    def __init__(self, index, timestamp, encrypted_data, previous_hash):
        self.index = index
        self.timestamp = timestamp
        self.encrypted_data = encrypted_data  # bytes
        self.previous_hash = previous_hash
        self.hash = self.compute_hash()

    def compute_hash(self):
        block_string = json.dumps({
            "index": self.index,
            "timestamp": self.timestamp,
            "encrypted_data": self.encrypted_data.decode(),
            "previous_hash": self.previous_hash
        }, sort_keys=True).encode()
        return hashlib.sha256(block_string).hexdigest()

class Blockchain:
    def __init__(self):
        self.chain = [self.create_genesis_block()]

    def create_genesis_block(self):
        return Block(0, time.time(), fernet.encrypt(b"Genesis Block"), "0")

    def add_block(self, data_dict):
        data_str = json.dumps(data_dict)
        encrypted_data = fernet.encrypt(data_str.encode())
        last_block = self.chain[-1]
        new_block = Block(len(self.chain), time.time(), encrypted_data, last_block.hash)
        self.chain.append(new_block)

    def display_chain(self):
        for block in self.chain:
            print(f"Index: {block.index}")
            print(f"Timestamp: {block.timestamp}")
            print(f"Encrypted Data (base64): {block.encrypted_data}")
            print(f"Decrypted Data: {fernet.decrypt(block.encrypted_data).decode(errors='ignore')}")
            print(f"Previous Hash: {block.previous_hash}")
            print(f"Hash: {block.hash}")
            print("-" * 50)

# Example: Store DataFrame in Blockchain
def store_dataframe(df, blockchain):
    for _, row in df.iterrows():
        blockchain.add_block(row.to_dict())

# Example usage
if __name__ == "__main__":
    # Create a sample DataFrame
    data = {
        "name": ["Alice", "Bob", "Charlie"],
        "age": [30, 25, 35],
        "medical_record": ["O+", "A-", "B+"]
    }
    df = pd.DataFrame(data)

    # Initialize and populate blockchain
    blockchain = Blockchain()
    store_dataframe(df, blockchain)
    blockchain.display_chain()

Index: 0
Timestamp: 1746087654.4507039
Encrypted Data (base64): b'gAAAAABoEy7m3ofa4xOySQS8osFrA0Kvn5h_IiKtTWHsoMTgU_ZdLFAglg8Vb9E8NeFmVjrwAQm6eSJ-aZ6_R3CNu9U0i5oaIA=='
Decrypted Data: Genesis Block
Previous Hash: 0
Hash: 7ce67e6321059f7ba382aecc223717deed7a213f60753a4e3a2c2d6d2635144e
--------------------------------------------------
Index: 1
Timestamp: 1746087654.4591088
Encrypted Data (base64): b'gAAAAABoEy7mGaAuWNHEf-EQeyoQJ1rrA2FU0AYpntVBlsh3RoWINDp1ySrBe82ED0yFP9WojI6S2L_a-wdTFotO9j7OL1iObmxrxZ6oLe-wSEdIyr0xYdg6vfNm9hyPciRg_UcuxN0HU-FrG5c-WH_pZ-9-8vFYeA=='
Decrypted Data: {"name": "Alice", "age": 30, "medical_record": "O+"}
Previous Hash: 7ce67e6321059f7ba382aecc223717deed7a213f60753a4e3a2c2d6d2635144e
Hash: 1831ce96ce0e448310cf4c715b25752fd8271529d13e65879979acee5e2cfd5f
--------------------------------------------------
Index: 2
Timestamp: 1746087654.4595733
Encrypted Data (base64): b'gAAAAABoEy7mOe2gLIqT2UmEiuSaPraIxWGaPfJkl9pU96gtjcwHowHWjx2zw21cQoZ_P66MSyCduZgckao89zqB0UQNcEtzKObcxAVAIf9cR2bXlgQ2NwGdqhVUwIrKYS0zusRVQ7GhoimrDfHsxf_tNM-IIhAHRw=='
Decrypted Data: {"name": "Bob", "age": 25, "medical_record": "A-"}
Previous Hash: 1831ce96ce0e448310cf4c715b25752fd8271529d13e65879979acee5e2cfd5f
Hash: b930d52a006185ef411eb47d6e4a4400b8d4e61d71733e2c4832d9358698abf1
--------------------------------------------------
Index: 3
Timestamp: 1746087654.4599595
Encrypted Data (base64): b'gAAAAABoEy7mJ-H2cxMT4RriO5NrpFIVCRUaZ3H-zDZZyjqo-JE9QDeUU82b8F7il0jDtADhNexqcTwOKMcLaQV7pH93IILu7VV1N-qskgIo-Rbo-dN-maIDlxGz_hE8KqoaUcV09kygrVq_dDFwWvLz0L1Hhesndw=='
Decrypted Data: {"name": "Charlie", "age": 35, "medical_record": "B+"}
Previous Hash: b930d52a006185ef411eb47d6e4a4400b8d4e61d71733e2c4832d9358698abf1
Hash: 1b37c15a3ea6d64de79cac6b4b4b05d225a4d15261d71eb86d10a92280c14e8d
--------------------------------------------------

In [6]:
import pandas as pd
import numpy as np
import json
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from flask import Flask, Response, request, jsonify
from web3 import Web3, HTTPProvider, EthereumTesterProvider
from solcx import install_solc, compile_source

install_solc(version='latest')

In [7]:
!git clone https://github.com/digvijaysingh1707/Blockchain_based_Federated_learning.git

Cloning into 'Blockchain_based_Federated_learning'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 19.27 KiB | 6.42 MiB/s, done.

In [8]:
df = pd.read_csv('Blockchain_based_Federated_learning/uci_malware_detection.csv')

In [9]:

y = df["Label"]
X = df.drop("Label", axis=1)

X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)

In [10]:
X_train

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_522,F_523,F_524,F_525,F_526,F_527,F_528,F_529,F_530,F_531
192,1,0,1,0,1,0,1,0,1,0,...,1,0,0,0,1,0,1,0,1,0
75,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,1,0,1,0
84,1,0,1,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,1,0
361,1,0,1,0,1,0,1,0,1,0,...,0,0,1,0,1,0,0,0,1,0
16,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
106,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
270,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
348,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,1,0,0,0,1,0
102,1,0,1,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [11]:
w3 = Web3(EthereumTesterProvider())
w3.is_connected()

<frozen importlib._bootstrap>:1047: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1047: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()

True

In [12]:
compiled_sol = compile_source(
    '''
    pragma solidity >0.5.0;

    contract ModelParameters {
        string public encoded;

        constructor() public {
            encoded = '';
        }

        function setModelParameters(string memory _encoded) public {
            encoded = _encoded;
        }

        function getModelParameters() view public returns (string memory) {
            return encoded;
        }
    }
    ''',
    output_values=['abi', 'bin']
)

contract_id, contract_interface = compiled_sol.popitem()
bytecode = contract_interface['bin']
abi = contract_interface['abi']

ModelParameters = w3.eth.contract(abi=abi, bytecode=bytecode)

tx_hash = ModelParameters.constructor().transact()
tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

ml_contract = w3.eth.contract(
    address=tx_receipt.contractAddress,
    abi=abi
)

In [13]:
cls = LogisticRegression()
cls.fit(X_train,y_train)

<frozen importlib._bootstrap>:1047: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1047: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()

LogisticRegression()

In [14]:
predictions = cls.predict(X_test);

accuracy = np.sum(predictions == y_test) / y_test.shape[0] * 100
conf_matrix = confusion_matrix(predictions, y_test)
precision = conf_matrix[0,0] / (conf_matrix[0,0] + conf_matrix[0,1]) * 100

print(conf_matrix)
print("Accuracy: {0:.6f}%".format(accuracy))
print("Precision: {0:.6f}%".format(precision))

[[57  1]
 [ 1 16]]
Accuracy: 97.333333%
Precision: 98.275862%

In [15]:
encoded = json.dumps((cls.coef_.tolist(), cls.intercept_.tolist(), cls.classes_.tolist()))
encoded

'[[[-0.002654774890015878, 0.0, -0.0052246612138527205, 0.002569886323836836, -0.0052246612138527205, 0.0, -0.0052246612138527205, 0.0, -0.0052246612138527205, 0.0, -0.0748442132326684, 0.0, 0.06647560919989288, 0.0, -0.06185413517636361, 0.0, 0.005063296884227979, 0.0, 0.28614423329762173, -0.39175684738651567, 0.1539673026842246, 0.0, 0.06738652803833539, 0.08658077464588923, 0.06738652803833539, -0.09570850993860179, 0.06738652803833539, 0.0, 0.1580485870321436, -0.1607033619221595, 0.1539673026842246, 0.0, 0.0771237519035868, 0.0, 0.00642145966599515, 0.09192105836478325, -0.09714571957863588, 0.09192105836478325, -0.09714571957863588, 4.878774934525946e-05, 0.06733774028899014, -0.10703616915963382, 0.06733774028899014, -0.07256240150284274, 0.06733774028899014, 0.07986251398318893, 0.18629698250443144, 0.02423772932974272, -0.2671520499623872, 0.26192738874853455, -0.2838883984454118, 0.179065986029245, -0.2647794524287589, 4.878774934525946e-05, 0.1865741682719344, 0.030917468339711908, -0.03614212955356457, 0.030917468339711908, -0.07278410087867407, 0.0701293259886583, -0.11767578165428356, 0.02423772932974272, 0.005063296884227979, 0.0926985079205321, 0.005063296884227979, 0.2399798400102872, -0.24263461490030294, 0.008934843037315057, 0.2896211327378812, 0.07353186030297247, 0.006408508288608038, 0.012042169028802223, 0.06324364056905911, 0.012042169028802223, 0.084769313208719, 0.0069093310515306264, 0.005063296884227979, 0.028585908437642134, -0.031240683327657937, 0.028585908437642134, 0.005063296884227979, -0.007718071774243872, 0.005063296884227979, -0.01028795809808068, 0.005063296884227979, 0.007536232691652926, 0.005063296884227979, 0.0, -0.14861198435964604, 0.0, 0.006470247415340408, -0.009125022305356346, 0.006470247415340408, 0.039863889341345986, 0.010351382295771807, 0.0, 0.015196937209178581, -0.11220546705013347, 0.006470247415340408, 0.11654106527644119, 0.006470247415340408, -0.009125022305356346, 0.006470247415340408, 0.006129282160540496, 0.006470247415340408, 0.006129282160540496, -0.03402545378621144, 0.006129282160540496, 0.005063296884227979, 0.0014069505311124298, 0.16680622709039275, 0.0014069505311124298, 0.1480261363566933, 0.0014069505311124298, 0.005063296884227979, -0.17634679165569245, 0.015831977161874077, 0.0014069505311124298, 0.005063296884227979, 0.0046312598045324125, 0.02945344304162801, 0.021824168177702098, -0.044641038134818116, 0.0014069505311124298, 0.001086512672774256, 0.02573097433465377, 0.14338705152999126, 0.0972710839159726, 0.11392535397236382, 0.0005298808959696528, 0.017920796421440614, -0.06529601357612955, 0.06264123868611383, 0.0005298808959696528, -0.1194402765553626, 0.017824786237409407, 0.005940366519370756, 0.09085238668007861, -0.3430951073661725, 0.3188999759121865, -0.22018293897345106, 0.007015415808997432, 0.06480576912976276, 0.006032261416387847, 0.00656726815949306, 0.08920217140987657, 0.00656726815949306, 0.00833300544833607, 0.026406900188307193, 0.008959907088458372, 0.005940366519370756, 0.006659163056510148, 0.03173117942071247, -0.034385954310728294, 0.03173117942071247, 0.08836696252140594, -0.15011401466812918, 0.019373044938862567, 0.005940366519370756, 0.038272503771868305, 0.07518757261906552, -0.22379955697871162, 0.036101785478757836, -0.038756560368773674, 0.036101785478757836, 0.006032261416387847, 0.00656726815949306, -0.00922204304950899, 0.00656726815949306, -0.09083132537584482, 0.06250934347557838, 0.011883409157917205, 0.005940366519370756, 0.011111700452377374, 0.1055727333594515, 0.016217495707151412, 0.06072736498182523, 0.016217495707151412, -0.290904884174658, 0.01296326246684232, 0.035980455841297596, -0.2572863497406541, 0.23470689696330077, 0.0, 0.005112084633573238, 0.1285470192681767, 0.011327155165278222, 0.06402314843419638, 0.12526074012099978, 0.0013581627817671705, 0.06729721720539669, 0.061923176338300266, -0.12496513232599595, 0.11974047111214331, 0.005738986273695539, 0.1468208067511434, 0.005112084633573238, 0.011813971632763959, 0.005112084633573238, -0.17639557940503764, 0.005112084633573238, 0.10244478360619601, 0.07097120496517696, 0.0, -0.19588198153011288, 0.0227886502230629, -0.2455659092418908, 0.02593614294514831, 0.044466438406766416, 0.024188941580397468, 0.005063296884227979, 0.06316101734509917, -0.06581579223511502, 0.007536232691652926, 0.008347195308785787, 0.03378982484252802, 0.005063296884227979, 0.0014069505311124298, -0.006631611744965129, 0.0014069505311124298, 0.005063296884227979, 0.0014069505311124298, 0.005063296884227979, 0.0014069505311124298, 0.011476596243088671, 0.0059314528084231325, -0.11882758645987217, 0.004406831757350053, 0.011476596243088671, 0.0, -0.0052246612138527205, 0.0, 0.011972627935758595, 0.08457435232114512, 0.022028841331193382, 0.058552430325516734, 0.074880648865993, -0.08010531007984567, 0.006470247415340408, 0.06091628062299498, 0.037426237407783454, 0.11513355561705554, 0.006470247415340408, 0.007040200998982988, 0.0603463270393524, 0.030318223740937962, 0.006470247415340408, 0.005502380520418196, 0.01141047631842728, -0.2694582458305523, 0.014354392674030325, 0.0, 0.006470247415340408, 0.07024279769495043, 0.031739295189658026, 0.006129282160540496, 0.006957938922560051, -0.022718954438978263, 0.006470247415340408, 0.07457736527399822, 0.013989010639473429, 0.006129282160540496, 0.005112084633573238, 0.06227444340476212, 0.005112084633573238, -0.289357805751721, 0.005112084633573238, -0.0897559053763132, 0.005112084633573238, 0.0068605433021853655, 0.031613510183253445, 0.0068605433021853655, 0.005063296884227979, -0.0023009873614938323, -0.014420300636363419, 0.011849559954617497, 0.02026220201379605, 0.24353434780526537, 0.031769967777949853, -0.034424742667965726, 0.014415176214449078, -0.12327057375474976, 0.09537440212907879, 0.008299156245036361, 0.005063296884227979, 0.010951840543666715, 0.005974215722670472, 0.08211121149119938, 0.059427872467434986, -0.208039856827081, 0.2053850819370654, 0.007536232691652926, 0.006453122077733711, 0.09287184778014436, 0.005063296884227979, -0.16046492577385668, 0.023696504136759316, 0.11380546955028217, 0.005063296884227979, 0.0847203839129601, 0.08370066839379035, 0.14373429627544723, 0.0059654305705140655, 0.024428550151131836, 0.09087781832778266, 0.007536232691652926, 0.005063296884227979, 0.024428550151131836, 0.04032524065176633, 0.002317869369554926, 0.005063296884227979, 0.0406134891495433, 0.005063296884227979, 0.10566519968303795, 0.005063296884227979, 0.17309294738039416, 0.005063296884227979, 0.24889883319774275, 0.005063296884227979, -0.2651200764219783, 0.09383658165051405, 0.01848493198516545, -0.1886715216676806, 0.08158345563799163, 0.005063296884227979, 0.0601048394214146, 0.005063296884227979, 0.008926057885158654, 0.005063296884227979, -0.150450971970454, 0.14522631075660147, 0.002317869369554926, 0.03364669989195988, -0.1920420148731654, 0.005063296884227979, 0.03391119922500861, 0.005063296884227979, 0.0069093310515306264, -0.12514499471716062, 0.0069093310515306264, -0.06795355568693161, 0.0069093310515306264, 0.10064753718823863, -0.14828007028020848, 0.005063296884227979, 0.026222793751632206, 0.005974215722670472, 0.03772596948176137, 0.005974215722670472, 0.04343245158718282, 0.005063296884227979, 0.14657161428837592, 0.02785194710729089, 0.019041246036834714, 0.005063296884227979, 0.0069093310515306264, 0.006601117362792774, 0.007502196525446585, 0.010565677404646173, -0.17488337087798003, 0.04708879794029838, 0.17420807613853506, 0.005063296884227979, 0.01073469613455192, 0.005063296884227979, -0.23482619363579452, 0.19195543063871712, 0.007536232691652926, -0.028721550459567983, 0.006221314788629689, 0.005063296884227979, 0.0014069505311124298, 0.07205877054199192, 0.0014069505311124298, 0.005063296884227979, 0.0069093310515306264, 0.005063296884227979, -0.01321001407177366, 0.010555239181757804, -0.16330819797211266, 0.005063296884227979, 0.0014069505311124298, 0.07095259181007717, 0.11751231129624352, -0.2915227996002702, 0.08692397357540771, 0.02939840322465074, 0.1298886462585311, 0.017043726786297834, 0.11840818612012435, 0.016132807947855356, 0.0014069505311124298, 0.06681736369821471, 0.14289183503114358, 0.011192579044768478, 0.03327385936199795, 0.005063296884227979, 0.0014069505311124298, -0.15001893489075852, 0.14479427367690587, 0.03727559385621801, 0.04406350324894482, -0.22479776427199416, 0.08271641228179953, 0.011994297934682445, 0.007820249889973116, 0.00708002371785601, 0.00856087378623903, -0.013785535000091687, 0.0069093310515306264, 0.005063296884227979, -0.007718071774243872, 0.005063296884227979, 0.007536232691652926, 0.039416296073245746, 0.010760541965072904, 0.14980448264791796, 0.22375407278771747, -0.17454815170665197, 0.16932349049279924, 0.012029530905176701, 0.1185049770939201, 0.005063296884227979, 0.054112017274134054, 0.007903504358503635, 0.01107448313028221, -0.030765836113072514, 0.0014069505311124298, 0.005974215722670472, 0.012476461594739804, -0.014262497988691062, 0.009037836774838385, 0.09332705077686737, 0.017550779507099663, -0.22896888274300856, 0.00416622375035645, 0.03880645840089102, 0.0149860324016568, 0.005063296884227979, 0.0, 0.0187511403914582, 0.005502380520418196, 0.007860072608846143, 0.006129282160540496, 0.006470247415340408, -0.15149883905077985, 0.14884406416076398, 0.0064132993588606885, -0.151645954592313, 0.0, -0.20749895174116512, 0.01797684679853936, 0.073236565808423, 0.11144479517810434, -0.11666945639195696, 0.0, -0.04272676714794142, 0.0, 0.07061083731175534, 0.0, 0.011972627935758595, 0.015780001011471055, 0.006470247415340408, 0.005502380520418196, 0.1204998735116203, -0.1099632197633761, 0.08206704813770511, 0.042598546357959906, 0.00848697424896844, 0.058101825913124516, 0.09627298022660467, 0.008298587437756366, 0.00709714905546271, 0.003224309273419981, 0.06197466569516723, -0.05714909519973334, 0.05376300263433363, 0.03500262916735311, 0.062178440576954, -0.01747378091739204, -0.11599026333833494, 0.0, 0.030805353755763144, 0.00242675473735917, 0.0135104484143234, 0.0, 0.014678711175671034, 0.0, -0.130872659224409, 0.0, -0.10881078708592766, 0.0, 0.006470247415340408, 0.010035667949885297, 0.006470247415340408, 0.005502380520418196, 0.1513953910396986, 0.005502380520418196, -0.12372840391322501, 0.05378037270619374, 0.06855316222306007, 0.07019879974453273, -0.07252581204705129, 0.02877141079150536, 0.07392128992251672, -0.06443209932488515, -0.04183628010963018, -0.052860021215698175, -0.06040123498961709, -0.03285326214002187, -0.046246197407699294, -0.0374432805088376, -0.04372973898756644, -0.05340291983166914, -0.05113568868976408, -0.040667311975263534, -0.05251320657296815, -0.04656671664599638, -0.049313062108850635, -0.05709245458457033, -0.04330926699126351, -0.04344772063619835, -0.04961283065156024, -0.04495898813102715, -0.04706459256387443, -0.2432814750569906, -0.02037559054379878, -0.04199098039574611, -0.05420194641998194, -0.22684738144421154, -0.09107588386095514]], [4.6371772977283126], ["malicious", "non-malicious"]]'

In [16]:
w3.eth.defaultAccount = w3.eth.accounts[0]

tx_hash = ml_contract.functions.setModelParameters(encoded).transact()

tx_receipt = w3.eth.wait_for_transaction_receipt(tx_hash)

<frozen importlib._bootstrap>:1047: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1047: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()

In [17]:
w3.eth.defaultAccount = w3.eth.accounts[1]

encoded_parameters = ml_contract.functions.getModelParameters().call()
encoded_parameters

'[[[-0.002654774890015878, 0.0, -0.0052246612138527205, 0.002569886323836836, -0.0052246612138527205, 0.0, -0.0052246612138527205, 0.0, -0.0052246612138527205, 0.0, -0.0748442132326684, 0.0, 0.06647560919989288, 0.0, -0.06185413517636361, 0.0, 0.005063296884227979, 0.0, 0.28614423329762173, -0.39175684738651567, 0.1539673026842246, 0.0, 0.06738652803833539, 0.08658077464588923, 0.06738652803833539, -0.09570850993860179, 0.06738652803833539, 0.0, 0.1580485870321436, -0.1607033619221595, 0.1539673026842246, 0.0, 0.0771237519035868, 0.0, 0.00642145966599515, 0.09192105836478325, -0.09714571957863588, 0.09192105836478325, -0.09714571957863588, 4.878774934525946e-05, 0.06733774028899014, -0.10703616915963382, 0.06733774028899014, -0.07256240150284274, 0.06733774028899014, 0.07986251398318893, 0.18629698250443144, 0.02423772932974272, -0.2671520499623872, 0.26192738874853455, -0.2838883984454118, 0.179065986029245, -0.2647794524287589, 4.878774934525946e-05, 0.1865741682719344, 0.030917468339711908, -0.03614212955356457, 0.030917468339711908, -0.07278410087867407, 0.0701293259886583, -0.11767578165428356, 0.02423772932974272, 0.005063296884227979, 0.0926985079205321, 0.005063296884227979, 0.2399798400102872, -0.24263461490030294, 0.008934843037315057, 0.2896211327378812, 0.07353186030297247, 0.006408508288608038, 0.012042169028802223, 0.06324364056905911, 0.012042169028802223, 0.084769313208719, 0.0069093310515306264, 0.005063296884227979, 0.028585908437642134, -0.031240683327657937, 0.028585908437642134, 0.005063296884227979, -0.007718071774243872, 0.005063296884227979, -0.01028795809808068, 0.005063296884227979, 0.007536232691652926, 0.005063296884227979, 0.0, -0.14861198435964604, 0.0, 0.006470247415340408, -0.009125022305356346, 0.006470247415340408, 0.039863889341345986, 0.010351382295771807, 0.0, 0.015196937209178581, -0.11220546705013347, 0.006470247415340408, 0.11654106527644119, 0.006470247415340408, -0.009125022305356346, 0.006470247415340408, 0.006129282160540496, 0.006470247415340408, 0.006129282160540496, -0.03402545378621144, 0.006129282160540496, 0.005063296884227979, 0.0014069505311124298, 0.16680622709039275, 0.0014069505311124298, 0.1480261363566933, 0.0014069505311124298, 0.005063296884227979, -0.17634679165569245, 0.015831977161874077, 0.0014069505311124298, 0.005063296884227979, 0.0046312598045324125, 0.02945344304162801, 0.021824168177702098, -0.044641038134818116, 0.0014069505311124298, 0.001086512672774256, 0.02573097433465377, 0.14338705152999126, 0.0972710839159726, 0.11392535397236382, 0.0005298808959696528, 0.017920796421440614, -0.06529601357612955, 0.06264123868611383, 0.0005298808959696528, -0.1194402765553626, 0.017824786237409407, 0.005940366519370756, 0.09085238668007861, -0.3430951073661725, 0.3188999759121865, -0.22018293897345106, 0.007015415808997432, 0.06480576912976276, 0.006032261416387847, 0.00656726815949306, 0.08920217140987657, 0.00656726815949306, 0.00833300544833607, 0.026406900188307193, 0.008959907088458372, 0.005940366519370756, 0.006659163056510148, 0.03173117942071247, -0.034385954310728294, 0.03173117942071247, 0.08836696252140594, -0.15011401466812918, 0.019373044938862567, 0.005940366519370756, 0.038272503771868305, 0.07518757261906552, -0.22379955697871162, 0.036101785478757836, -0.038756560368773674, 0.036101785478757836, 0.006032261416387847, 0.00656726815949306, -0.00922204304950899, 0.00656726815949306, -0.09083132537584482, 0.06250934347557838, 0.011883409157917205, 0.005940366519370756, 0.011111700452377374, 0.1055727333594515, 0.016217495707151412, 0.06072736498182523, 0.016217495707151412, -0.290904884174658, 0.01296326246684232, 0.035980455841297596, -0.2572863497406541, 0.23470689696330077, 0.0, 0.005112084633573238, 0.1285470192681767, 0.011327155165278222, 0.06402314843419638, 0.12526074012099978, 0.0013581627817671705, 0.06729721720539669, 0.061923176338300266, -0.12496513232599595, 0.11974047111214331, 0.005738986273695539, 0.1468208067511434, 0.005112084633573238, 0.011813971632763959, 0.005112084633573238, -0.17639557940503764, 0.005112084633573238, 0.10244478360619601, 0.07097120496517696, 0.0, -0.19588198153011288, 0.0227886502230629, -0.2455659092418908, 0.02593614294514831, 0.044466438406766416, 0.024188941580397468, 0.005063296884227979, 0.06316101734509917, -0.06581579223511502, 0.007536232691652926, 0.008347195308785787, 0.03378982484252802, 0.005063296884227979, 0.0014069505311124298, -0.006631611744965129, 0.0014069505311124298, 0.005063296884227979, 0.0014069505311124298, 0.005063296884227979, 0.0014069505311124298, 0.011476596243088671, 0.0059314528084231325, -0.11882758645987217, 0.004406831757350053, 0.011476596243088671, 0.0, -0.0052246612138527205, 0.0, 0.011972627935758595, 0.08457435232114512, 0.022028841331193382, 0.058552430325516734, 0.074880648865993, -0.08010531007984567, 0.006470247415340408, 0.06091628062299498, 0.037426237407783454, 0.11513355561705554, 0.006470247415340408, 0.007040200998982988, 0.0603463270393524, 0.030318223740937962, 0.006470247415340408, 0.005502380520418196, 0.01141047631842728, -0.2694582458305523, 0.014354392674030325, 0.0, 0.006470247415340408, 0.07024279769495043, 0.031739295189658026, 0.006129282160540496, 0.006957938922560051, -0.022718954438978263, 0.006470247415340408, 0.07457736527399822, 0.013989010639473429, 0.006129282160540496, 0.005112084633573238, 0.06227444340476212, 0.005112084633573238, -0.289357805751721, 0.005112084633573238, -0.0897559053763132, 0.005112084633573238, 0.0068605433021853655, 0.031613510183253445, 0.0068605433021853655, 0.005063296884227979, -0.0023009873614938323, -0.014420300636363419, 0.011849559954617497, 0.02026220201379605, 0.24353434780526537, 0.031769967777949853, -0.034424742667965726, 0.014415176214449078, -0.12327057375474976, 0.09537440212907879, 0.008299156245036361, 0.005063296884227979, 0.010951840543666715, 0.005974215722670472, 0.08211121149119938, 0.059427872467434986, -0.208039856827081, 0.2053850819370654, 0.007536232691652926, 0.006453122077733711, 0.09287184778014436, 0.005063296884227979, -0.16046492577385668, 0.023696504136759316, 0.11380546955028217, 0.005063296884227979, 0.0847203839129601, 0.08370066839379035, 0.14373429627544723, 0.0059654305705140655, 0.024428550151131836, 0.09087781832778266, 0.007536232691652926, 0.005063296884227979, 0.024428550151131836, 0.04032524065176633, 0.002317869369554926, 0.005063296884227979, 0.0406134891495433, 0.005063296884227979, 0.10566519968303795, 0.005063296884227979, 0.17309294738039416, 0.005063296884227979, 0.24889883319774275, 0.005063296884227979, -0.2651200764219783, 0.09383658165051405, 0.01848493198516545, -0.1886715216676806, 0.08158345563799163, 0.005063296884227979, 0.0601048394214146, 0.005063296884227979, 0.008926057885158654, 0.005063296884227979, -0.150450971970454, 0.14522631075660147, 0.002317869369554926, 0.03364669989195988, -0.1920420148731654, 0.005063296884227979, 0.03391119922500861, 0.005063296884227979, 0.0069093310515306264, -0.12514499471716062, 0.0069093310515306264, -0.06795355568693161, 0.0069093310515306264, 0.10064753718823863, -0.14828007028020848, 0.005063296884227979, 0.026222793751632206, 0.005974215722670472, 0.03772596948176137, 0.005974215722670472, 0.04343245158718282, 0.005063296884227979, 0.14657161428837592, 0.02785194710729089, 0.019041246036834714, 0.005063296884227979, 0.0069093310515306264, 0.006601117362792774, 0.007502196525446585, 0.010565677404646173, -0.17488337087798003, 0.04708879794029838, 0.17420807613853506, 0.005063296884227979, 0.01073469613455192, 0.005063296884227979, -0.23482619363579452, 0.19195543063871712, 0.007536232691652926, -0.028721550459567983, 0.006221314788629689, 0.005063296884227979, 0.0014069505311124298, 0.07205877054199192, 0.0014069505311124298, 0.005063296884227979, 0.0069093310515306264, 0.005063296884227979, -0.01321001407177366, 0.010555239181757804, -0.16330819797211266, 0.005063296884227979, 0.0014069505311124298, 0.07095259181007717, 0.11751231129624352, -0.2915227996002702, 0.08692397357540771, 0.02939840322465074, 0.1298886462585311, 0.017043726786297834, 0.11840818612012435, 0.016132807947855356, 0.0014069505311124298, 0.06681736369821471, 0.14289183503114358, 0.011192579044768478, 0.03327385936199795, 0.005063296884227979, 0.0014069505311124298, -0.15001893489075852, 0.14479427367690587, 0.03727559385621801, 0.04406350324894482, -0.22479776427199416, 0.08271641228179953, 0.011994297934682445, 0.007820249889973116, 0.00708002371785601, 0.00856087378623903, -0.013785535000091687, 0.0069093310515306264, 0.005063296884227979, -0.007718071774243872, 0.005063296884227979, 0.007536232691652926, 0.039416296073245746, 0.010760541965072904, 0.14980448264791796, 0.22375407278771747, -0.17454815170665197, 0.16932349049279924, 0.012029530905176701, 0.1185049770939201, 0.005063296884227979, 0.054112017274134054, 0.007903504358503635, 0.01107448313028221, -0.030765836113072514, 0.0014069505311124298, 0.005974215722670472, 0.012476461594739804, -0.014262497988691062, 0.009037836774838385, 0.09332705077686737, 0.017550779507099663, -0.22896888274300856, 0.00416622375035645, 0.03880645840089102, 0.0149860324016568, 0.005063296884227979, 0.0, 0.0187511403914582, 0.005502380520418196, 0.007860072608846143, 0.006129282160540496, 0.006470247415340408, -0.15149883905077985, 0.14884406416076398, 0.0064132993588606885, -0.151645954592313, 0.0, -0.20749895174116512, 0.01797684679853936, 0.073236565808423, 0.11144479517810434, -0.11666945639195696, 0.0, -0.04272676714794142, 0.0, 0.07061083731175534, 0.0, 0.011972627935758595, 0.015780001011471055, 0.006470247415340408, 0.005502380520418196, 0.1204998735116203, -0.1099632197633761, 0.08206704813770511, 0.042598546357959906, 0.00848697424896844, 0.058101825913124516, 0.09627298022660467, 0.008298587437756366, 0.00709714905546271, 0.003224309273419981, 0.06197466569516723, -0.05714909519973334, 0.05376300263433363, 0.03500262916735311, 0.062178440576954, -0.01747378091739204, -0.11599026333833494, 0.0, 0.030805353755763144, 0.00242675473735917, 0.0135104484143234, 0.0, 0.014678711175671034, 0.0, -0.130872659224409, 0.0, -0.10881078708592766, 0.0, 0.006470247415340408, 0.010035667949885297, 0.006470247415340408, 0.005502380520418196, 0.1513953910396986, 0.005502380520418196, -0.12372840391322501, 0.05378037270619374, 0.06855316222306007, 0.07019879974453273, -0.07252581204705129, 0.02877141079150536, 0.07392128992251672, -0.06443209932488515, -0.04183628010963018, -0.052860021215698175, -0.06040123498961709, -0.03285326214002187, -0.046246197407699294, -0.0374432805088376, -0.04372973898756644, -0.05340291983166914, -0.05113568868976408, -0.040667311975263534, -0.05251320657296815, -0.04656671664599638, -0.049313062108850635, -0.05709245458457033, -0.04330926699126351, -0.04344772063619835, -0.04961283065156024, -0.04495898813102715, -0.04706459256387443, -0.2432814750569906, -0.02037559054379878, -0.04199098039574611, -0.05420194641998194, -0.22684738144421154, -0.09107588386095514]], [4.6371772977283126], ["malicious", "non-malicious"]]'

In [18]:
decoded_parameters = json.loads(encoded_parameters)
cls_global = LogisticRegression()

cls_global.coef_ = np.array(decoded_parameters[0])
cls_global.intercept_ = np.array(decoded_parameters[1])
cls_global.classes_ = np.array(decoded_parameters[2])

In [19]:
predictions = cls_global.predict(X_test);
result = pd.DataFrame(np.vstack((predictions, y_test)).T,columns=['Predicted Outcomes','Actual Outcomes'])
result

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

  Predicted Outcomes Actual Outcomes
0          malicious       malicious
1      non-malicious   non-malicious
2      non-malicious   non-malicious
3          malicious       malicious
4      non-malicious   non-malicious

In [21]:
accuracy = np.sum(predictions == y_test) / y_test.shape[0] * 100
conf_matrix = confusion_matrix(predictions, y_test)
precision = conf_matrix[0,0] / (conf_matrix[0,0] + conf_matrix[0,1]) * 100

print(conf_matrix)
print("Accuracy: {0:.6f}%".format(accuracy))
print("Precision: {0:.6f}%".format(precision))

[[57  1]
 [ 1 16]]
Accuracy: 97.333333%
Precision: 98.275862%